package main

import (
	"fmt"
	"strings"
)

func checkGray(ctx *Context) []Check {
	d := ctx.M()
	bits := integer(d["bits"])
	steps := integer(d["steps"])
	states := []int{}
	for n := 0; n < steps; n++ {
		states = append(states, grayN(n))
	}
	mask := (1 << bits) - 1
	adj := []int{}
	for i := 0; i < steps; i++ {
		adj = append(adj, bitCount(states[i]^states[(i+1)%steps]))
	}
	pref := []string{}
	for _, s := range states[:8] {
		pref = append(pref, fmt.Sprintf("%0*b", bits, s))
	}
	wrap := fmt.Sprintf("%0*b -> %0*b", bits, states[len(states)-1], bits, states[0])
	uniq := map[int]bool{}
	inside := true
	for _, s := range states {
		uniq[s] = true
		inside = inside && s >= 0 && s <= mask
	}
	adjacent := true
	for _, d := range adj[:len(adj)-1] {
		adjacent = adjacent && d == 1
	}
	return []Check{{"the JSON requests the full 4-bit state space", bits == 4 && steps == 1<<bits}, {"states are generated by n xor (n >> 1)", len(states) == steps && states[5] == grayN(5)}, {"all generated states stay inside the 4-bit mask", inside}, {"all generated states are unique", len(uniq) == integer(asMap(d["expected"])["uniqueStates"])}, {"each adjacent transition flips exactly one bit", adjacent}, {"the wrap transition also flips exactly one bit", adj[len(adj)-1] == integer(asMap(d["expected"])["wrapHammingDistance"])}, {"the reported sequence prefix matches reflected binary Gray code", contains(ctx.Answer, "sequence prefix : "+strings.Join(pref, ", "))}, {"the reported wrap transition matches recomputation", contains(ctx.Answer, "wrap transition : "+wrap)}, {"the reported maximum adjacent Hamming distance is one", fieldInt(ctx.Answer, "maximum adjacent Hamming distance") == maxInt(adj)}}
}
