# Independent Python checks for the gray_code_counter example.
from __future__ import annotations

import re

from .common import run_checks


def gray(n: int) -> int:
    return n ^ (n >> 1)


def hamming(a: int, b: int) -> int:
    return (a ^ b).bit_count()


def parse_int(answer: str, label: str) -> int | None:
    match = re.search(rf"{re.escape(label)}\s*:\s*([0-9]+)", answer)
    return int(match.group(1)) if match else None


def run(ctx):
    data = ctx.load_input()
    bits = int(data["bits"])
    steps = int(data["steps"])
    states = [gray(n) for n in range(steps)]
    mask = (1 << bits) - 1
    adjacent = [hamming(states[i], states[(i + 1) % steps]) for i in range(steps)]
    prefix = ", ".join(f"{state:0{bits}b}" for state in states[:8])
    wrap = f"{states[-1]:0{bits}b} -> {states[0]:0{bits}b}"

    checks = [
        ("the JSON requests the full 4-bit state space", bits == 4 and steps == 1 << bits),
        ("states are generated by n xor (n >> 1)", states == [n ^ (n >> 1) for n in range(steps)]),
        ("all generated states stay inside the 4-bit mask", all(0 <= s <= mask for s in states)),
        ("all generated states are unique", len(set(states)) == data["expected"]["uniqueStates"]),
        ("each adjacent transition flips exactly one bit", all(distance == 1 for distance in adjacent[:-1])),
        ("the wrap transition also flips exactly one bit", adjacent[-1] == data["expected"]["wrapHammingDistance"]),
        ("the reported sequence prefix matches reflected binary Gray code", f"sequence prefix : {prefix}" in ctx.answer),
        ("the reported wrap transition matches recomputation", f"wrap transition : {wrap}" in ctx.answer),
        ("the reported maximum adjacent Hamming distance is one", parse_int(ctx.answer, "maximum adjacent Hamming distance") == max(adjacent)),
    ]
    return run_checks(checks)
